FROM node:18-alpine

# Override DNS to bypass India ban
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf
RUN echo "nameserver 8.8.4.4" >> /etc/resolv.conf
RUN echo "nameserver 1.1.1.1" >> /etc/resolv.conf

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

EXPOSE 3000
CMD ["npm", "start"]
